version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  
  frontend:
    working_dir: /frontend
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
